/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pantallas;
import com.dtos.EmpleadoDTO;
import com.dtos.MedicoDTO;
import com.persistencias.UsuarioPersistencia;
import java.time.LocalDate;
import javax.swing.JOptionPane;
/**
 *
 * @author martinez
 */
public class frmRegistrar extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistrar
     */
    public frmRegistrar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfNombreCompleto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txfNumeroTelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTipoEmpleado = new javax.swing.JLabel();
        txfNombreUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txfCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txfContrasena = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        dtpFechaNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        chbMedico = new javax.swing.JCheckBox();
        chbEmpleado = new javax.swing.JCheckBox();
        chbEmpleado.setSelected(true);
        jPanel1 = new javax.swing.JPanel();
        txfNumeroCedula = new javax.swing.JTextField();
        cobTipoEmpleado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre completo");

        jLabel2.setText("Numero telefono");

        jLabel3.setText("Fecha nacimiento");

        lblTipoEmpleado.setText("Tipo empleado");

        jLabel5.setText("Nombre de Usuario");

        jLabel6.setText("Correo");

        jLabel7.setText("Contraseña");

        jLabel8.setText("Tipo usuario");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });

        chbMedico.setText("Medico");
        chbMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbMedicoActionPerformed(evt);
            }
        });

        chbEmpleado.setText("Empleado");
        chbEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbEmpleadoActionPerformed(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(73, 22));
        jPanel1.setLayout(null);

        txfNumeroCedula.setVisible(false);
        txfNumeroCedula.setEnabled(false);
        jPanel1.add(txfNumeroCedula);
        txfNumeroCedula.setBounds(6, 0, 280, 22);

        cobTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Empleado" }));
        cobTipoEmpleado.setMinimumSize(new java.awt.Dimension(64, 22));
        cobTipoEmpleado.setPreferredSize(new java.awt.Dimension(64, 22));
        jPanel1.add(cobTipoEmpleado);
        cobTipoEmpleado.setBounds(10, 0, 140, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txfContrasena)
                    .addComponent(txfCorreo)
                    .addComponent(txfNombreUsuario)
                    .addComponent(txfNumeroTelefono)
                    .addComponent(txfNombreCompleto)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoEmpleado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtpFechaNacimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(chbMedico)
                        .addGap(18, 18, 18)
                        .addComponent(chbEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btnRegistrar)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfNumeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dtpFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(lblTipoEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbMedico)
                    .addComponent(chbEmpleado)
                    .addComponent(btnRegistrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        UsuarioPersistencia up = new UsuarioPersistencia();
        String nombreUsuario = txfNombreUsuario.getText().trim();
        LocalDate fechaNacimiento = dtpFechaNacimiento.getDate();
        
        if(!up.nombreUsuarioExiste(nombreUsuario)) {
            if(chbEmpleado.isSelected()){
                EmpleadoDTO edto = new EmpleadoDTO(
                        txfNombreCompleto.getText().trim(),
                        txfNumeroTelefono.getText().trim(),
                        fechaNacimiento,
                        cobTipoEmpleado.getItemAt(cobTipoEmpleado.getSelectedIndex())
                );
                edto.setNombreUsuario(nombreUsuario);
                edto.setCorreo(txfCorreo.getText().trim());
                edto.setContrasena(txfContrasena.getText().trim());
                edto.setTipoUsuario("empleado");
            
                up.agregarUsuarioEmpleado(edto);
                JOptionPane.showMessageDialog(null, "Usuario Registrado con éxito", "Operacion exitosa", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else if(chbMedico.isSelected()) {
                MedicoDTO mdto = new MedicoDTO(
                        txfNombreCompleto.getText().trim(),
                        txfNumeroTelefono.getText().trim(),
                        txfNumeroCedula.getText().trim(),
                        fechaNacimiento
                );
                mdto.setNombreUsuario(nombreUsuario);
                mdto.setCorreo(txfCorreo.getText().trim());
                mdto.setContrasena(txfContrasena.getText().trim());
                mdto.setTipoUsuario("medico");
            
                up.agregarMedico(mdto);
                JOptionPane.showMessageDialog(null, "Usuario Registrado con éxito", "Operacion exitosa", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Este nombre de usuario ya existe", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void chbMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbMedicoActionPerformed
        chbMedico.setSelected(true);
        chbEmpleado.setSelected(false);
        lblTipoEmpleado.setText("Cédula Profesional");
        cobTipoEmpleado.setVisible(false);
        cobTipoEmpleado.setEnabled(false);
        txfNumeroCedula.setVisible(true);
        txfNumeroCedula.setEnabled(true);
    }//GEN-LAST:event_chbMedicoActionPerformed

    private void chbEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbEmpleadoActionPerformed
        chbMedico.setSelected(false);
        chbEmpleado.setSelected(true);
        lblTipoEmpleado.setText("Tipo empleado");
        cobTipoEmpleado.setVisible(true);
        cobTipoEmpleado.setEnabled(true);
        txfNumeroCedula.setVisible(false);
        txfNumeroCedula.setEnabled(false);
    }//GEN-LAST:event_chbEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox chbEmpleado;
    private javax.swing.JCheckBox chbMedico;
    private javax.swing.JComboBox<String> cobTipoEmpleado;
    private com.github.lgooddatepicker.components.DatePicker dtpFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTipoEmpleado;
    private javax.swing.JTextField txfContrasena;
    private javax.swing.JTextField txfCorreo;
    private javax.swing.JTextField txfNombreCompleto;
    private javax.swing.JTextField txfNombreUsuario;
    private javax.swing.JTextField txfNumeroCedula;
    private javax.swing.JTextField txfNumeroTelefono;
    // End of variables declaration//GEN-END:variables
}
