/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pantallas.empleado;

import com.control.InventarioControl;
import com.control.Sesion;
import com.control.SucursalControl;
import com.dtos.InventarioSucursalDTO;
import com.dtos.SucursalDTO;
import com.persistencias.SucursalPersistencia;
import com.servicios.ConversionesTablas;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author pausa
 */
public class frmInventarioMedicamentos extends javax.swing.JFrame {

    /**
     * Creates new form frmInventarioMedicamentos
     */
    public frmInventarioMedicamentos() {
        convers = new ConversionesTablas();
        invControl = new InventarioControl();
        sucursalSeleccionada = Sesion.getSucursalEmpleado();
        scrslControl = new SucursalControl();
        scrslPersistencia = new SucursalPersistencia();
        listaSucursales = scrslPersistencia.listaSucursales();
        listaInventario = new ArrayList<>();
        initComponents();
        setLocationRelativeTo(null);
        DefaultTableModel modelo = (DefaultTableModel) tblInventario.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(modelo);
        tblInventario.setRowSorter(sorter);
        actualizarTablaMedicamentos(listaInventario);
    }
    
    private void actualizarTablaMedicamentos(List<InventarioSucursalDTO> listaMedicamentos) {
        this.tblInventario.setModel(convers.listaMedicamentosInventarioToTableModel(listaMedicamentos));
        this.tblInventario.getColumnModel().removeColumn(tblInventario.getColumnModel().getColumn(3));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txfNombreMedicamento = new javax.swing.JTextField();
        btnBuscarMedicamento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        btnAgregarMedicamento = new javax.swing.JButton();
        btnActualizarMedicamento = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cobListaSucursales = new javax.swing.JComboBox<>();
        cobListaSucursales.setModel(invControl.listaSucursalesToComboBoxModel(listaSucursales));
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miRealizarVenta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miConsultarRecetas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miConsultarInventario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        if(!Sesion.getUsuarioLogueado().getTipoUsuario().equals("Gerente")){
            jMenu4.setVisible(false);
            jMenu4.setEnabled(false);
        }
        miAgregarSucursal = new javax.swing.JMenuItem();
        menLabelSucursal = new javax.swing.JMenu();
        menLabelSucursal.setEnabled(false);
        menLabelSucursal.setText(Sesion.getSucursalEmpleado().getNombreSucursal());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Medicamento");

        btnBuscarMedicamento.setText("Buscar");
        btnBuscarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMedicamentoActionPerformed(evt);
            }
        });

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicamento", "Activo", "Presentacion", "Precio", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInventario);
        if (tblInventario.getColumnModel().getColumnCount() > 0) {
            tblInventario.getColumnModel().getColumn(0).setResizable(false);
            tblInventario.getColumnModel().getColumn(1).setResizable(false);
            tblInventario.getColumnModel().getColumn(2).setResizable(false);
            tblInventario.getColumnModel().getColumn(3).setResizable(false);
            tblInventario.getColumnModel().getColumn(4).setResizable(false);
        }

        btnAgregarMedicamento.setText("Nuevo");
        btnAgregarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregar(evt);
            }
        });

        btnActualizarMedicamento.setText("Actualizar");
        btnActualizarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizar(evt);
            }
        });

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelar(evt);
            }
        });

        jLabel2.setText("Sucursal");

        cobListaSucursales.setSelectedItem(sucursalSeleccionada);
        cobListaSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobListaSucursalesActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setText("Venta");

        miRealizarVenta.setText("Realizar Venta");
        miRealizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRealizarVentaActionPerformed(evt);
            }
        });
        jMenu1.add(miRealizarVenta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Recetas");

        miConsultarRecetas.setText("Consultar Recetas");
        miConsultarRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarRecetasActionPerformed(evt);
            }
        });
        jMenu2.add(miConsultarRecetas);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Inventario");

        miConsultarInventario.setText("Consultar Inventario");
        miConsultarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarInventarioActionPerformed(evt);
            }
        });
        jMenu3.add(miConsultarInventario);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sucursal");

        miAgregarSucursal.setText("Crear Sucursal");
        miAgregarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgregarSucursalActionPerformed(evt);
            }
        });
        jMenu4.add(miAgregarSucursal);

        jMenuBar1.add(jMenu4);

        menLabelSucursal.setToolTipText("");
        jMenuBar1.add(Box.createHorizontalGlue());
        jMenuBar1.add(menLabelSucursal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btnAgregarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cobListaSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txfNombreMedicamento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfNombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMedicamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cobListaSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarMedicamento)
                    .addComponent(btnActualizarMedicamento)
                    .addComponent(jButton5))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonActualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizar
        int seleccion = tblInventario.getSelectedRow();
        InventarioSucursalDTO invActualizar = listaInventario.get(seleccion);
        InventarioSucursalDTO invActualizado = invControl.actualizarInventario(invActualizar);
        listaInventario.set(seleccion, invActualizado);
    }//GEN-LAST:event_BotonActualizar

    private void BotonAgregar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregar
        InventarioSucursalDTO inventario = invControl.agregarMedicamento();
        listaInventario.add(inventario);
        actualizarTablaMedicamentos(listaInventario);
    }//GEN-LAST:event_BotonAgregar

    private void BotonCancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelar
        frmInicioEmpleadoFarmacia frmAM= new frmInicioEmpleadoFarmacia();
        frmAM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonCancelar

    private void miRealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRealizarVentaActionPerformed
        frmVenta venta = new frmVenta();
        venta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miRealizarVentaActionPerformed

    private void miConsultarRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarRecetasActionPerformed
        frmRecetas recetas = new frmRecetas();
        recetas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miConsultarRecetasActionPerformed

    private void miConsultarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarInventarioActionPerformed
    }//GEN-LAST:event_miConsultarInventarioActionPerformed

    private void cobListaSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobListaSucursalesActionPerformed
        int seleccion = cobListaSucursales.getSelectedIndex();
        String nombreSucursalSeleccionada = cobListaSucursales.getItemAt(seleccion);
        if(!nombreSucursalSeleccionada.equalsIgnoreCase(Sesion.getSucursalEmpleado().getNombreSucursal())) {
            btnAgregarMedicamento.setVisible(false);
            btnAgregarMedicamento.setEnabled(false);
            btnActualizarMedicamento.setVisible(false);
            btnActualizarMedicamento.setEnabled(false);
            sucursalSeleccionada = scrslPersistencia.obtenerSucursalPorNombre(nombreSucursalSeleccionada);
            listaInventario = invControl.listaInventarioSucursal(sucursalSeleccionada);
            actualizarTablaMedicamentos(listaInventario);
        } else {
            btnAgregarMedicamento.setVisible(true);
            btnAgregarMedicamento.setEnabled(true);
            btnActualizarMedicamento.setVisible(true);
            btnActualizarMedicamento.setEnabled(true);
            sucursalSeleccionada = Sesion.getSucursalEmpleado();
            listaInventario = invControl.listaInventarioSucursal(sucursalSeleccionada);
            actualizarTablaMedicamentos(listaInventario);
        }
    }//GEN-LAST:event_cobListaSucursalesActionPerformed

    private void btnBuscarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMedicamentoActionPerformed
        String nombreMedicamento = txfNombreMedicamento.getText().trim();
        if(nombreMedicamento.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingresa el nombre de un medicamento para poder buscarlo", "Advertencia", JOptionPane.WARNING_MESSAGE);
            sorter.setRowFilter(null);
        } else {
            try {
                sorter.setRowFilter(RowFilter.regexFilter("^" + nombreMedicamento, 0));
            } catch(NullPointerException e) {
                JOptionPane.showMessageDialog(this, "No existe un medicamento bajo ese nombre", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuscarMedicamentoActionPerformed

    private void miAgregarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgregarSucursalActionPerformed
        scrslControl.crearSucursal();
    }//GEN-LAST:event_miAgregarSucursalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInventarioMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInventarioMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInventarioMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInventarioMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInventarioMedicamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarMedicamento;
    private javax.swing.JButton btnAgregarMedicamento;
    private javax.swing.JButton btnBuscarMedicamento;
    private javax.swing.JComboBox<String> cobListaSucursales;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menLabelSucursal;
    private javax.swing.JMenuItem miAgregarSucursal;
    private javax.swing.JMenuItem miConsultarInventario;
    private javax.swing.JMenuItem miConsultarRecetas;
    private javax.swing.JMenuItem miRealizarVenta;
    private javax.swing.JTable tblInventario;
    private javax.swing.JTextField txfNombreMedicamento;
    // End of variables declaration//GEN-END:variables
    private SucursalDTO sucursalSeleccionada;
    private ConversionesTablas convers;
    private List<SucursalDTO> listaSucursales;
    private List<InventarioSucursalDTO> listaInventario;
    private SucursalPersistencia scrslPersistencia;
    private InventarioControl invControl;
    private SucursalControl scrslControl;
    TableRowSorter<TableModel> sorter;
    
}